---
K8S_VERSION: "1.33"
WORKDIR: "~/Build_K8S"
ARCH: "amd64"
Cluster_NAME: "lide_k8s"
CONTAINERD_VERSION: "2.1.4"
RUNC_VERSION: "1.3.0"
CNI_VERSION: "1.7.1"
K8S_POD_NETWORK_CIDR: "10.10.0.0/16"
K8S_SERVICE_CIDR: "10.88.0.0/16"
K8S_FQDN: "k8s.lide.tw"
